import logging
from dataclasses import dataclass, field


@dataclass
class ArchitectureReviewResult:
    request_id: str
    architecture_type: str
    resources: list[str] = field(default_factory=list)
    status: str = "pending_approval"
    recommendation: str = "APPROVE"
    comments: list[str] = field(default_factory=list)


def review_architecture_request(review: dict) -> ArchitectureReviewResult:
    """
    Review an architecture generated by the infrastructure agent.

    This is the initial deterministic reviewer.
    Later this component can be replaced or enhanced with an LLM.
    """

    request_id = review["request_id"]
    architecture_type = review["architecture_type"]
    resources = review.get("resources", [])

    comments = []

    # Basic validation
    if not architecture_type:
        comments.append("Missing architecture type.")

    if not resources:
        comments.append("No Azure resources were defined.")

    # Initial recommendation
    if comments:
        recommendation = "REJECT"
    else:
        recommendation = "APPROVE"
        comments.append(
            "Architecture contains the required structural components "
            "for initial review."
        )

    result = ArchitectureReviewResult(
        request_id=request_id,
        architecture_type=architecture_type,
        resources=resources,
        status="pending_approval",
        recommendation=recommendation,
        comments=comments,
    )

    logging.info(
        "Architecture review completed: %s",
        result
    )

    return result