import json
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass
class TerraformGenerationResult:
    request_id: str
    status: str
    output_directory: str
    files: list[str]
    message: str


def _terraform_name(value: str) -> str:
    """
    Convierte un valor en un identificador seguro.
    """

    normalized = "".join(
        character.lower() if character.isalnum() else "-"
        for character in value
    )

    normalized = normalized.strip("-")

    return normalized or "azure-infra"


def _generate_main_tf(
    architecture: dict[str, Any]
) -> str:

    request_id = architecture["request_id"]

    architecture_type = architecture.get(
        "architecture_type",
        ""
    )

    resources = architecture.get(
        "resources",
        []
    )

    environment = architecture.get(
        "environment",
        "dev"
    )

    safe_request_id = _terraform_name(
        request_id
    )

    storage_suffix = safe_request_id.replace(
        "-",
        ""
    )

    storage_name = (
        f"stgen{storage_suffix}"
    )[:24]

    return f'''# ============================================================
# GENERATED BY AZURE INFRA AGENT
# ============================================================
#
# Request ID: {request_id}
# Architecture: {architecture_type}
# Environment: {environment}
#
# This Terraform configuration was generated from an
# APPROVED architecture.
# ============================================================

terraform {{
  required_version = ">= 1.5.0"

  required_providers {{
    azurerm = {{
      source  = "hashicorp/azurerm"
      version = "4.81.0"
    }}
  }}
}}

provider "azurerm" {{
  features {{}}

  resource_provider_registrations = "none"
  storage_use_azuread = true
}}

# ============================================================
# RESOURCE GROUP
# ============================================================

resource "azurerm_resource_group" "generated" {{

  name = "rg-generated-{safe_request_id}"

  location = var.location

  tags = {{
    Environment = var.environment
    ManagedBy   = "Azure-Infrastructure-Agent"
    RequestId   = "{request_id}"
  }}
}}

# ============================================================
# STORAGE ACCOUNT
# ============================================================

resource "azurerm_storage_account" "generated" {{

  name = "{storage_name}"

  resource_group_name = (
    azurerm_resource_group.generated.name
  )

  location = (
    azurerm_resource_group.generated.location
  )

  account_tier = "Standard"

  account_replication_type = "LRS"

  min_tls_version = "TLS1_2"

  https_traffic_only_enabled = true

  # ----------------------------------------------------------
  # SECURITY HARDENING
  # ----------------------------------------------------------

  public_network_access_enabled = false

  allow_nested_items_to_be_public = false

  shared_access_key_enabled = false

  local_user_enabled = false

  tags = {{
    Environment = var.environment
    ManagedBy   = "Azure-Infrastructure-Agent"
    RequestId   = "{request_id}"
  }}
}}

# ============================================================
# STORAGE CONTAINER
# ============================================================

resource "azurerm_storage_container" "generated" {{

  name = "data"

  storage_account_id = (
    azurerm_storage_account.generated.id
  )

  container_access_type = "private"
}}

# ============================================================
# ARCHITECTURE INFORMATION
# ============================================================
#
# Generated from approved architecture resources:
#
# {json.dumps(resources, ensure_ascii=False)}
#
# ============================================================
'''


def _generate_variables_tf() -> str:

    return '''# ============================================================
# VARIABLES
# ============================================================

variable "location" {

  description = "Azure deployment region."

  type = string

  default = "eastus"
}


variable "environment" {

  description = "Deployment environment."

  type = string

  default = "dev"

  validation {

    condition = contains(
      ["dev", "test", "prod"],
      var.environment
    )

    error_message = "Environment must be dev, test or prod."
  }
}
'''


def _generate_outputs_tf() -> str:

    return '''# ============================================================
# OUTPUTS
# ============================================================

output "resource_group_name" {

  value = azurerm_resource_group.generated.name
}


output "storage_account_name" {

  value = azurerm_storage_account.generated.name
}


output "storage_account_id" {

  value = azurerm_storage_account.generated.id
}


output "storage_container_name" {

  value = azurerm_storage_container.generated.name
}
'''


def _generate_tfvars(
    architecture: dict[str, Any]
) -> str:
    """
    Generates Terraform variable values from the approved
    architecture dictionary.
    """

    environment = str(
        architecture.get(
            "environment",
            "dev"
        )
    ).strip().lower()

    return f'''# ============================================================
# GENERATED BY AZURE INFRA AGENT
# ============================================================
#
# Terraform variable values generated from the
# approved architecture.
# ============================================================

environment = "{environment}"
'''


def generate_terraform(
    architecture: dict[str, Any],
    output_root: str = "generated"
) -> TerraformGenerationResult:
    """
    Generates Terraform configuration from an approved
    architecture dictionary.
    """

    if not isinstance(
        architecture,
        dict
    ):

        raise TypeError(
            "architecture must be a dictionary"
        )

    # --------------------------------------------------------
    # Validate request_id
    # --------------------------------------------------------

    request_id = architecture.get(
        "request_id"
    )

    if not request_id:

        raise ValueError(
            "Missing required field: request_id"
        )

    request_id = str(
        request_id
    ).strip()

    # --------------------------------------------------------
    # Validate decision
    # --------------------------------------------------------

    decision = str(
        architecture.get(
            "decision",
            ""
        )
    ).strip().upper()

    if decision != "APPROVED":

        raise ValueError(
            "Terraform generation requires decision APPROVED"
        )

    # --------------------------------------------------------
    # Create output directory
    # --------------------------------------------------------

    safe_request_id = _terraform_name(
        request_id
    )

    output_directory = (
        Path(output_root)
        / safe_request_id
    )

    output_directory.mkdir(
        parents=True,
        exist_ok=True
    )

    # --------------------------------------------------------
    # Generate Terraform files
    # --------------------------------------------------------

    files = {

        "main.tf":
            _generate_main_tf(
                architecture
            ),

        "variables.tf":
            _generate_variables_tf(),

        "terraform.tfvars":
            _generate_tfvars(
                architecture
            ),

        "outputs.tf":
            _generate_outputs_tf()
    }

    generated_files = []

    for filename, content in files.items():

        file_path = (
            output_directory
            / filename
        )

        file_path.write_text(
            content,
            encoding="utf-8"
        )

        generated_files.append(
            str(file_path)
        )

        logging.info(
            "Terraform file generated: %s",
            file_path
        )

    # --------------------------------------------------------
    # Completed
    # --------------------------------------------------------

    logging.info(
        "Terraform generation completed successfully: %s",
        request_id
    )

    return TerraformGenerationResult(

        request_id=request_id,

        status="terraform_generated",

        output_directory=str(
            output_directory
        ),

        files=generated_files,

        message=(
            "Terraform configuration generated "
            "successfully."
        )
    )